#!/bin/sh
"""": # -*-python-*-
bup_python="$(dirname "$0")/../cmd/bup-python" || exit $?
exec "$bup_python" "$0" ${1+"$@"}
"""
# end of bup preamble

from __future__ import print_function
from sys import exit, stderr
import sys

if sys.platform.startswith('cygwin'):
    getwv = getattr(sys, 'getwindowsversion', None)
    if not getwv:
        msg = "don't know how to detect root status; assuming not root"
    elif getwv()[0] > 5:
        # Sounds like the situation is much more complicated for > 5
        msg = "can't detect root status for OS version > 5; assuming not root"
    if msg:
        print(msg, file=stderr)
        print('none')
    else:
        import ctypes
        if ctypes.cdll.shell32.IsUserAnAdmin():
            print('root')
        else:
            print('none')
    exit(0)

import os
if os.environ.get('FAKEROOTKEY'):
    print('fake')
else:
    print('root' if os.geteuid() == 0 else 'none')
